image: alpine:latest

stages:
  - Static Analysis
  - Test
  - Build

variables:
  # disable Docker TLS validation
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

include:
  - local: /ci/build.gitlab-ci.yml