image: alpine:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  ROLLOUT_RESOURCE_TYPE: deployment

stages:
  - build
  - static analysis
  - test
  - release
  - staging
  - production

include:
  - project: 'cloudnua-public/gitops/infra/templates'
    ref: main
    file:
      - 'build.gitlab-ci.yml'
      - 'test-py-2.gitlab-ci.yml'
      - 'deploy.gitlab-ci.yml'