image: alpine:latest

stages:
  - Build
  - Static Analysis
  - Test
  - Release

variables:
  # disable Docker TLS validation
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

include:
  - local: /ci/build.gitlab-ci.yml
  - local: /ci/test.gitlab-ci.yml
