version: '3.8'

services:
  streamlit:
    build:
      dockerfile: ./dockerfile
      context: ./
    ports:
      - '8501:8501'
    volumes:
      - './src:/usr/src/app/project:delegated'
    environment:
      - USER_ID=1000
      - GROUP_ID=1000